version: "3"

services:
  postgres:
    image: postgres:alpine
    volumes:
      - ./topjava/doc/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ib
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin